#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dxvk
Version  : 1.4.4
Release  : 1
URL      : https://github.com/doitsujin/dxvk/archive/v1.4.4.tar.gz
Source0  : https://github.com/doitsujin/dxvk/archive/v1.4.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause Zlib
Requires: dxvk-license = %{version}-%{release}
BuildRequires : Vulkan-Loader-dev
BuildRequires : Vulkan-Loader-dev32
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : glslang
BuildRequires : mingw-binutils
BuildRequires : pkgconfig(32vulkan)
BuildRequires : pkgconfig(vulkan)
BuildRequires : util-linux
BuildRequires : wine
BuildRequires : wine-dev
BuildRequires : wine-dev32
BuildRequires : wine-extras-staticdev

%description
# DXVK
A Vulkan-based translation layer for Direct3D 10/11 which allows running 3D applications on Linux using Wine.

%package license
Summary: license components for the dxvk package.
Group: Default

%description license
license components for the dxvk package.


%prep
%setup -q -n dxvk-1.4.4

%build
## build_prepend content
meson --cross-file build-wine64.txt --buildtype release --prefix `pwd -P`/64 build.w64
pushd build.w64
ninja install
popd
meson --cross-file build-wine32.txt --buildtype release --prefix `pwd -P`/32 build.w32
pushd build.w32
ninja install
popd
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572292515
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}  ||:


%install
export SOURCE_DATE_EPOCH=1572292515
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dxvk
cp %{_builddir}/dxvk-1.4.4/LICENSE %{buildroot}/usr/share/package-licenses/dxvk/4a83b2fbabc7965ffeffdda9b49248867c18e621
cp %{_builddir}/dxvk-1.4.4/include/openvr/LICENSE %{buildroot}/usr/share/package-licenses/dxvk/99e40ce3676d57f631fca8692017203185ab6b5f
%make_install ||:

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dxvk/4a83b2fbabc7965ffeffdda9b49248867c18e621
/usr/share/package-licenses/dxvk/99e40ce3676d57f631fca8692017203185ab6b5f
